Todo-List AddandRemoveTask
maths29/Todo-List pull request #2
Opened 2023-06-16 16:34 UTC by maths29

in this project I:
- add another js file to dynamically generate the content
- and improved the style.css

2023-06-16 17:01 UTC, Ismailco requested changes
### Hi @maths29, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used GitHub Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 17:01 UTC, Ismailco commented on src/index.js
> +
- [ ] Kindly make sure to remove all the commented code from your code base, this will make the code more organized and easy to navigate

2023-06-16 17:01 UTC, Ismailco commented on src/index.html
>              <input class="add-input" type="text" placeholder="Add to your list..." required>
- [ ] [OPTIONAL] Kindly make sure to fix this bug in the UI so it looks nicer

![Screenshot_20230616_175916](https://github.com/maths29/Todo-List/assets/25227022/d16c625f-4179-4f13-916b-ee8d57a4afc8)

2023-06-17 07:09 UTC, Shedrack-Sunday approved these changes
Hi @maths29     👋

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

![image](https://i.pinimg.com/originals/3d/d2/07/3dd207237b39dcacd832f94a35428255.gif)


## Highlights
- Good job with the use of GitHub features✔️ 
- Kudos on fixing the changes as requested ✔️ 

## Optional Suggestions 💡
While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.
Cheers, and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread, and don't forget to tag me so I'll receive the notification.

As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-17 07:24 UTC, merged